# main text of home
name: Nicodemo  Zilli
bio: Code it, Run it, Live it!
aboutme:
    I'm a Computer Systems Engineer, specializing in Web Engineering.
    Full Stack Web Developer, interested in the ethical development of Artificial Intelligence.
    With the ability to learn and apply my knowledge in the professional field.
    Looking for an opportunity where I can develop my skills and gain experience.

#Résumé

lastupdate: 19 de enero 2022

# Experience section
experience:
  item1:
    position: Java Backend Developer
    company: TecNM CENIDET
    from: August 2021
    to: December 2021
    description: >
      Developing a Backend Java application for calculating quality metrics of software architectures
    link:
  reference: https://nicodemozilli.github.io/resume/

# Education section
education:
  item1:
    institution: Tecnológico Nacional de México Campus Orizaba / ITO
    program: Computerstystems Engineering.
    description: Specialty in Web Engineering.
    from: August 2017
    to: December 2021
  item2:
    institution: Centro de Bachillerato Tecnológico Industrial y de Servicios No. 47 CBTIS No. 47
    program: Support and Maintenance of Computer Equipment Technician.
    description: Administration and repair of computer equipment and networks.
    cedprof: CED. PROF. 12557082
    from: August 2014
    to: July 2017

# Production
production:
  item1:
    event: Coloquio de Investigación Multidisciplinaria CIM Octubre 2018, TecNM campus Orizaba
    topic: Educational Research, "Análisis de la realidad del aprendizaje de programación en el Instituto Tecnológico de Orizaba"
    material: static/docs/material-CIM2018.pdf
    link: http://cim.orizaba.tecnm.mx/?page_id=161

# Certifications and awards section
courses:
  - Open Data Science 21-25 October 2019
  - Arduino and Some Applications 15-27 October 2019
  - Master Programmer 12 September 2019
  - Git Version Control June 2019
  - Python Programming 21-25 October 2017

# Skills section
skills:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - java
  - python
  - php
  - html5
  - css3
  - js
  - react
  - wordpress
  - cpanel
  - markdown
  - git
  - github
  - gitlab
  - digital-ocean
  - aws
  - google
  - apple
  - linux
  - centos
  - Web development, full stack, MySQL PostgreSQL
  - Machine learning con ML.js
  - Java development, full stack
  - Arduino and Internet of things
  - Cross Platform App Development with AJAX and JSON
  - Data Administrator on MySQL and PostgreSQL



# twitter summary info
description: A portfolio about my own projects and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.jpg

# your site color theme, false to light theme
dark-theme: true

# If you want to include your resume, set to true
# and specify source (external or local).
resume: true
resume-external: false
resume-url: resume
#resume-url: https://nicodemozilli.glitch.me

url: https://nicodemozilli.github.io
# your url: https://USERNAME.github.io

permalink: /:title/

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# if you don't want comments in your posts, leave categories empty
# disqus:
#   shortname: nicodemozilli-github-io # enter this from your disqus account
#   categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
facebook: nzillivazquez
twitter: ZvNico
instagram: nicodemozilli
linkedin: nicodemozilli
github: NicodemoZilli
email: nicozv13@gmail.com

authors:
  nicodemozilli:
    name: Nicodemo Zilli
    bio: Code it, Run it, Live it!
    external-image: false
    picture: assets/images/profile.jpg
    twitter: ZvNico

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you do/don't need pagination, toggle 'enabled' between true/false below
pagination:
  enabled: false
  sort_reverse: true # display recent posts first
  title: ":title" # Changing this will mess up the header display logic
  per_page: 5
  permalink: "/:num/" # pagination link that will be appended

# if you don't need projects, comment the *projects* configs below
projects: true

# if you don't need "about" or "blog", comment them out below
about: true
blog: false

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

# add default values to specific pages or layouts
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      layout: "post"
    values:
      # setting all post to not hidden by default,
      # can be overridden in the front matter for a specific post
      hidden: false

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-include-cache

jekyll-mentions:
  base_url: https://github.com

compress_html:
  ignore:
    envs:
      - development
      - stage

exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
